# Generated by Django 6.1 on 2026-09-16 11:24

import django.db.models.deletion
import django.utils.timezone
import food_catering.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='fa-utensils', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8)),
                ('is_veg', models.BooleanField(default=True, help_text='True for Veg (Green), False for Non-Veg (Red)')),
                ('is_jain', models.BooleanField(default=False, help_text='Prepared without onion, garlic, or root vegetables')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.8'), max_digits=3)),
                ('preparation_time', models.PositiveIntegerField(default=15, help_text='Minutes needed to prepare')),
                ('image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_catering.foodcategory')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['-is_bestseller', 'price'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(db_index=True, default=food_catering.models.generate_food_order_ref, max_length=40, unique=True)),
                ('pnr', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('train_number', models.CharField(max_length=30)),
                ('train_name', models.CharField(max_length=150)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_time_slot', models.CharField(blank=True, default='Estimated on train arrival', max_length=50)),
                ('coach', models.CharField(help_text='e.g. B1, S4, A1', max_length=10)),
                ('seat_number', models.CharField(help_text='e.g. 12, 45', max_length=10)),
                ('passenger_name', models.CharField(max_length=120)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Order Confirmed'), ('PREPARING', 'Preparing in Kitchen'), ('OUT_FOR_DELIVERY', 'Out for Delivery at Station'), ('DELIVERED', 'Delivered to Seat'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=30)),
                ('payment_method', models.CharField(default='UPI', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid Online'), ('CASH_ON_DELIVERY', 'Pay on Delivery (Cash/UPI to Delivery Agent)'), ('REFUNDED', 'Refunded')], default='PAID', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_deliveries', to='railways.railwaystation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Order',
                'verbose_name_plural': 'Food Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('is_veg', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_catering.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_catering.foodorder')),
            ],
        ),
        migrations.CreateModel(
            name='StationRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cuisine', models.CharField(help_text='e.g. North Indian, Thalis, Biryani, Street Food', max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.8'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=120)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Free delivery or nominal charge', max_digits=6)),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=6)),
                ('is_pure_veg', models.BooleanField(default=False)),
                ('fssai_license', models.CharField(default='FSSAI-10020089123841', max_length=50)),
                ('image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='railways.railwaystation')),
            ],
            options={
                'verbose_name': 'Station Restaurant',
                'verbose_name_plural': 'Station Restaurants',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='food_catering.stationrestaurant'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food_catering.stationrestaurant'),
        ),
    ]
