# Generated by Django 6.1 on 2026-09-14 10:51

import datetime
import django.db.models.deletion
import hotels.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_seed_default_promocodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fa-solid fa-check', help_text='FontAwesome icon e.g. fa-solid fa-wifi', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=True, help_text='Show in quick highlights')),
            ],
            options={
                'verbose_name': 'Hotel Amenity',
                'verbose_name_plural': 'Hotel Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=250)),
                ('hotel_type', models.CharField(choices=[('LUXURY', 'Luxury Hotel & 5-Star Resort'), ('HERITAGE', 'Heritage Palace & Royal Haveli'), ('BUSINESS', 'Premium Business Hotel'), ('BOUTIQUE', 'Boutique & Lifestyle Stay'), ('RESORT', 'Beach & Nature Resort'), ('BUDGET', 'Comfort & Budget Stay')], default='LUXURY', max_length=30)),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star ★'), (2, '2 Star ★★'), (3, '3 Star ★★★'), (4, '4 Star ★★★★'), (5, '5 Star ★★★★★')], db_index=True, default=4)),
                ('guest_rating', models.DecimalField(db_index=True, decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=85)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('landmark', models.CharField(blank=True, help_text='e.g. Near New Delhi Railway Station / 2km from Airport', max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.CharField(help_text='URL or static asset image path', max_length=500)),
                ('check_in_time', models.TimeField(default=datetime.time(14, 0))),
                ('check_out_time', models.TimeField(default=datetime.time(11, 0))),
                ('cancellation_policy', models.TextField(default='Free cancellation up to 24 hours before check-in date. Cancellations within 24 hours incur a 1-night room charge.')),
                ('house_rules', models.TextField(blank=True, default='Government-issued Photo ID required for all adult guests at check-in (Aadhaar, Passport, DL). Couples welcome with valid ID proof.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelamenity')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-is_featured', '-guest_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, default=hotels.models.generate_hotel_booking_ref, max_length=30, unique=True)),
                ('room_count', models.PositiveIntegerField(default=1)),
                ('guest_count', models.PositiveIntegerField(default=2)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_out_date', models.DateField(db_index=True)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('primary_guest_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='e.g. Non-smoking room, high floor, early check-in', null=True)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='nights * rooms * price_per_night', max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, help_text='Hotel GST (12%)', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('49.00'), help_text='Platform Convenience Fee', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed / Checked Out'), ('REFUNDED', 'Refund Processed')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refund Processed')], default='PENDING', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.hotel')),
                ('promo_code_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='bookings.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Reservation',
                'verbose_name_plural': 'Hotel Reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotels.hotelbooking')),
            ],
            options={
                'verbose_name': 'Hotel Guest',
                'verbose_name_plural': 'Hotel Guests',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Gallery Image',
                'verbose_name_plural': 'Hotel Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('stay_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Review',
                'verbose_name_plural': 'Hotel Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='e.g. Deluxe Room, Executive Suite, Luxury Royal Suite', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('bed_type', models.CharField(default='1 King Bed or 2 Twin Beds', max_length=100)),
                ('room_size_sqft', models.PositiveIntegerField(default=320, help_text='Room area in sq. ft.')),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=1)),
                ('max_occupancy', models.PositiveIntegerField(default=3)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Base rate per night (₹)', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted promo rate', max_digits=10, null=True)),
                ('total_rooms', models.PositiveIntegerField(default=10)),
                ('available_rooms', models.PositiveIntegerField(default=10)),
                ('image_url', models.CharField(blank=True, help_text='Room photo URL or static path', max_length=500)),
                ('has_free_breakfast', models.BooleanField(default=True)),
                ('has_free_cancellation', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_city_view', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('custom_facilities', models.CharField(blank=True, default='LED Smart TV, Mini Refrigerator, Tea/Coffee Maker, Electronic Safe, Rain Shower', help_text='Comma-separated amenities', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['price_per_night'],
            },
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.room'),
        ),
    ]
