# Generated by Django 5.2.7 on 2026-08-23 11:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Railway Station',
                'verbose_name_plural': 'Railway Stations',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('train_type', models.CharField(choices=[('VANDE_BHARAT', 'Vande Bharat Express'), ('RAJDHANI', 'Rajdhani Express'), ('SHATABDI', 'Shatabdi Express'), ('DURONTO', 'Duronto Express'), ('SUPERFAST', 'Superfast Express'), ('EXPRESS', 'Mail / Express')], default='SUPERFAST', max_length=30)),
                ('total_coaches', models.PositiveIntegerField(default=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('fare_general', models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=8)),
                ('fare_sleeper', models.DecimalField(decimal_places=2, default=Decimal('480.00'), max_digits=8)),
                ('fare_ac3', models.DecimalField(decimal_places=2, default=Decimal('1250.00'), max_digits=8)),
                ('fare_ac2', models.DecimalField(decimal_places=2, default=Decimal('1850.00'), max_digits=8)),
                ('fare_first_class', models.DecimalField(decimal_places=2, default=Decimal('2950.00'), max_digits=8)),
                ('runs_on', models.CharField(default='Daily (All 7 Days)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trains', to='railways.railwaystation')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_trains', to='railways.railwaystation')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='railways.train')),
            ],
            options={
                'verbose_name': 'Train Schedule',
                'verbose_name_plural': 'Train Schedules',
                'ordering': ['journey_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(help_text='Coach e.g. S1, B1, A1, H1, D1', max_length=10)),
                ('seat_number', models.CharField(help_text='Seat or Berth No e.g. 12', max_length=10)),
                ('berth_type', models.CharField(choices=[('LOWER', 'Lower Berth'), ('MIDDLE', 'Middle Berth'), ('UPPER', 'Upper Berth'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper'), ('CHAIR_CAR', 'Chair Car Window/Aisle'), ('CABIN', 'First AC Coupe/Cabin')], default='LOWER', max_length=20)),
                ('travel_class', models.CharField(choices=[('GENERAL', 'General (2S)'), ('SLEEPER', 'Sleeper (SL)'), ('AC_3_TIER', 'AC 3 Tier (3A)'), ('AC_2_TIER', 'AC 2 Tier (2A)'), ('FIRST_CLASS', 'Executive / First AC (1A)')], default='SLEEPER', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='railways.trainschedule')),
            ],
            options={
                'verbose_name': 'Train Seat',
                'verbose_name_plural': 'Train Seats',
                'ordering': ['coach', 'id'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'coach', 'seat_number'), name='unique_train_seat_per_schedule')],
            },
        ),
    ]
