# Generated by Django 6.1 on 2026-09-16 11:24

import django.db.models.deletion
import retiring_rooms.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('railways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRetiringRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AC_DORMITORY', 'AC Dormitory Bed'), ('NON_AC_STANDARD', 'Non-AC Standard Room'), ('AC_DELUXE', 'AC Deluxe Double Room'), ('EXECUTIVE_SUITE', 'Executive Station Suite')], db_index=True, default='AC_DELUXE', max_length=30)),
                ('room_or_bed_no', models.CharField(help_text='e.g. Bed D-04 or Room 208', max_length=30)),
                ('floor', models.CharField(default='Platform 1, 1st Floor Concourse', max_length=100)),
                ('price_12h', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Rate for 12 hours slot', max_digits=8)),
                ('price_24h', models.DecimalField(decimal_places=2, default=Decimal('900.00'), help_text='Rate for 24 hours full day', max_digits=8)),
                ('price_48h', models.DecimalField(decimal_places=2, default=Decimal('1650.00'), help_text='Rate for 48 hours', max_digits=8)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('amenities', models.CharField(default='Free High-Speed WiFi, Air Conditioning, Hot Water Shower, Clean Linen, Personal Locker, Charging Station', max_length=300)),
                ('image_url', models.CharField(default='https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiring_rooms', to='railways.railwaystation')),
            ],
            options={
                'verbose_name': 'Station Retiring Room / Bed',
                'verbose_name_plural': 'Station Retiring Rooms & Beds',
                'ordering': ['station', 'room_type', 'price_12h'],
            },
        ),
        migrations.CreateModel(
            name='RetiringRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(db_index=True, default=retiring_rooms.models.generate_retiring_room_ref, max_length=30, unique=True)),
                ('slot_type', models.CharField(choices=[('12_HOURS', '12 Hours Slot'), ('24_HOURS', '24 Hours (Full Day)'), ('48_HOURS', '48 Hours (2 Days)')], default='24_HOURS', max_length=20)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_in_time_slot', models.CharField(default='08:00 AM - 08:00 PM', max_length=50)),
                ('check_out_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_age', models.PositiveIntegerField(default=30)),
                ('guest_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID')], default='AADHAAR', max_length=30)),
                ('guest_id_number', models.CharField(max_length=50)),
                ('train_pnr', models.CharField(blank=True, default='', help_text='Associated Train PNR (optional)', max_length=30)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Payment Successful'), ('PENDING', 'Pending Payment'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20)),
                ('payment_method', models.CharField(default='UPI', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='railways.railwaystation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiring_room_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='retiring_rooms.stationretiringroom')),
            ],
            options={
                'verbose_name': 'Retiring Room Booking',
                'verbose_name_plural': 'Retiring Room Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
