# Generated by Django 6.1 on 2026-09-16 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=120)),
                ('reviewer_city', models.CharField(default='New Delhi', max_length=100)),
                ('booking_type', models.CharField(choices=[('TRAIN', 'Train / Railway'), ('FLIGHT', 'Flight / Airline'), ('BUS', 'Bus Travel'), ('HOTEL', 'Hotel & Resort'), ('FOOD', 'Food in Train (E-Catering)'), ('RETIRING_ROOM', 'Station Retiring Room'), ('OVERALL', 'Overall Platform Experience')], db_index=True, default='OVERALL', max_length=30)),
                ('pnr_or_ref', models.CharField(blank=True, help_text='Associated PNR or Booking Reference', max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, default='', help_text='e.g. Vande Bharat 22436 / Taj Hotel Goa', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Overall rating between 1 and 5')),
                ('punctuality_rating', models.PositiveSmallIntegerField(default=5)),
                ('cleanliness_rating', models.PositiveSmallIntegerField(default=5)),
                ('service_rating', models.PositiveSmallIntegerField(default=5)),
                ('value_rating', models.PositiveSmallIntegerField(default=5)),
                ('verified_traveler', models.BooleanField(default=True)),
                ('travel_tag', models.CharField(blank=True, default='Verified Traveler', help_text='e.g. Family Trip, Solo Traveler, Business', max_length=100)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='experiences.customerreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'session_key')},
            },
        ),
    ]
