# Generated by Django 5.2.7 on 2026-08-23 11:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_number', models.CharField(default='+91 1800-102-3344', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus Operator',
                'verbose_name_plural': 'Bus Operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_city', models.CharField(db_index=True, max_length=100)),
                ('destination_city', models.CharField(db_index=True, max_length=100)),
                ('boarding_points', models.TextField(help_text='Comma separated boarding points')),
                ('dropping_points', models.TextField(help_text='Comma separated dropping points')),
                ('distance_km', models.PositiveIntegerField(default=350)),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
                'ordering': ['source_city', 'destination_city'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bus_type', models.CharField(choices=[('ORDINARY', 'Ordinary Express'), ('AC_SEATER', 'AC Seater (2+2)'), ('AC_SLEEPER', 'AC Sleeper (2+1)'), ('VOLVO', 'Volvo Multi-Axle Luxury AC'), ('SEMI_SLEEPER', 'Premium Semi-Sleeper AC')], default='VOLVO', max_length=30)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('is_ac', models.BooleanField(default=True)),
                ('has_sleeper', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='buses.busoperator')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Journey duration in minutes')),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('850.00'), max_digits=8)),
                ('amenities', models.TextField(default='Air Conditioning, Free High-Speed WiFi, USB Charging Ports, Water Bottle, Clean Blankets, GPS Live Tracking')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buses.busroute')),
            ],
            options={
                'verbose_name': 'Bus Schedule',
                'verbose_name_plural': 'Bus Schedules',
                'ordering': ['journey_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='e.g. L1, L2, U1, 14', max_length=10)),
                ('deck', models.CharField(choices=[('LOWER', 'Lower Deck'), ('UPPER', 'Upper Deck')], default='LOWER', max_length=10)),
                ('seat_type', models.CharField(choices=[('SEATER', 'Pushback Seater'), ('SLEEPER', 'Single / Double Sleeper Berth')], default='SEATER', max_length=20)),
                ('is_ladies_only', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.busschedule')),
            ],
            options={
                'verbose_name': 'Bus Seat',
                'verbose_name_plural': 'Bus Seats',
                'ordering': ['deck', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'seat_number'), name='unique_bus_seat_per_schedule')],
            },
        ),
    ]
