# Generated by Django 5.2.7 on 2026-08-23 11:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='e.g. Airbus A320neo, Boeing 737 MAX 8, Boeing 787-9', max_length=100)),
                ('total_capacity', models.PositiveIntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='e.g. AI, 6E, UK, SG, QP', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_icon', models.CharField(default='fa-plane', max_length=50)),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='IATA 3-letter code e.g. DEL, BOM', max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('terminal', models.CharField(default='Terminal 1 / 2', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, help_text='e.g. 6E-2041, AI-805', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airlines.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines.airline')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['flight_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(db_index=True)),
                ('arrival_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Flight duration in minutes')),
                ('stops', models.PositiveIntegerField(default=0, help_text='0 for Non-stop, 1 for 1 stop')),
                ('fare_economy', models.DecimalField(decimal_places=2, default=Decimal('4200.00'), max_digits=9)),
                ('fare_premium_economy', models.DecimalField(decimal_places=2, default=Decimal('6800.00'), max_digits=9)),
                ('fare_business', models.DecimalField(decimal_places=2, default=Decimal('14500.00'), max_digits=9)),
                ('fare_first_class', models.DecimalField(decimal_places=2, default=Decimal('26000.00'), max_digits=9)),
                ('baggage_allowance', models.CharField(default='15 Kg Check-in + 7 Kg Cabin', max_length=100)),
                ('meal_included', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airlines.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='airlines.flight')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airlines.airport')),
            ],
            options={
                'verbose_name': 'Flight Schedule',
                'verbose_name_plural': 'Flight Schedules',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='e.g. 1A, 12F, 24C', max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('column_letter', models.CharField(max_length=2)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy Class'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business Class'), ('FIRST_CLASS', 'First Class Suite')], default='ECONOMY', max_length=20)),
                ('seat_type', models.CharField(choices=[('WINDOW', 'Window Seat'), ('AISLE', 'Aisle Seat'), ('MIDDLE', 'Middle Seat'), ('EXTRA_LEGROOM', 'Extra Legroom')], default='AISLE', max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airlines.flightschedule')),
            ],
            options={
                'verbose_name': 'Flight Seat',
                'verbose_name_plural': 'Flight Seats',
                'ordering': ['row_number', 'column_letter'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'seat_number'), name='unique_flight_seat_per_schedule')],
            },
        ),
    ]
