# Generated by Django 5.2.7 on 2026-08-23 11:54

import bookings.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
        ('buses', '0001_initial'),
        ('railways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, default=bookings.models.generate_unique_pnr, max_length=30, unique=True)),
                ('transport_type', models.CharField(choices=[('TRAIN', 'Train / Railway'), ('FLIGHT', 'Flight / Airline'), ('BUS', 'Bus Travel')], max_length=20)),
                ('service_title', models.CharField(help_text='e.g. Vande Bharat Express 22436 / AI-805 / IntrCity SmartBus', max_length=200)),
                ('travel_class', models.CharField(max_length=50)),
                ('source_location', models.CharField(max_length=150)),
                ('destination_location', models.CharField(max_length=150)),
                ('journey_date', models.DateField(db_index=True)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('duration_text', models.CharField(blank=True, max_length=50)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('allocated_seats', models.CharField(help_text='Comma-separated seat numbers e.g. B1-12, B1-13', max_length=200)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST / Airport Tax', max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Platform Convenience Fee', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refund Processed')], default='PENDING', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_bookings', to='buses.busschedule')),
                ('flight_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_bookings', to='airlines.flightschedule')),
                ('train_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_bookings', to='railways.trainschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('PAN_CARD', 'PAN Card')], default='AADHAAR', max_length=30)),
                ('id_number', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=20)),
                ('berth_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'ordering': ['id'],
            },
        ),
    ]
