# Generated by Django 6.1 on 2026-09-13 06:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Uppercase promo code e.g. TRAVELNOW', max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. Flight Special Discount', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Details regarding offer eligibility')),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount (₹)'), ('PERCENT', 'Percentage (%)')], default='FIXED', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Discount value in ₹ or %', max_digits=10)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum total booking fare required', max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage promos', max_digits=10, null=True)),
                ('applicable_transport', models.CharField(choices=[('ALL', 'All Transports'), ('FLIGHT', 'Flights Only'), ('TRAIN', 'Trains Only'), ('BUS', 'Buses Only')], default='ALL', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, help_text='Leave blank for no expiration', null=True)),
                ('usage_limit', models.PositiveIntegerField(default=1000, help_text='Max times this promo code can be used in total')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Times this promo code has been redeemed')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Max usages per single customer account')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Applied promo code string', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.promocode'),
        ),
    ]
